# Generated by Django 2.2.3 on 2019-07-31 18:15

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Verification', '0001_initial'),
        ('MetaData', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthentication',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('bio', models.CharField(max_length=255, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('linkedIn', models.URLField(blank=True, max_length=255, null=True)),
                ('github', models.URLField(blank=True, max_length=255, null=True)),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('gmail', models.EmailField(max_length=254, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('profile_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MetaData.UserProfileType')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MetaData.State')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verification', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Verification.UserProfileVerification')),
            ],
        ),
        migrations.CreateModel(
            name='NodeStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NodeOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
