# Generated by Django 2.2.3 on 2019-07-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.IntegerField(blank=True, null=True)),
                ('aadharPhoto', models.ImageField(blank=True, null=True, upload_to='')),
                ('panCard', models.CharField(blank=True, max_length=12, null=True)),
                ('panCardPhoto', models.ImageField(blank=True, null=True, upload_to='')),
                ('otherIdProof', models.CharField(blank=True, max_length=16, null=True)),
                ('otherIdProofImage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
