# Generated by Django 2.2.3 on 2019-07-31 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Automation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followerCount', models.IntegerField(null=True)),
                ('followers', models.ManyToManyField(related_name='Followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followingCount', models.IntegerField(null=True)),
                ('user_following', models.ManyToManyField(related_name='Following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestFriend', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('bestFriendCount', models.IntegerField(null=True)),
                ('friends', models.ManyToManyField(related_name='Friends', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.ImageField(null=True, upload_to='')),
                ('likeType', models.IntegerField(choices=[(1, 'Heart'), (2, 'Laugh'), (3, 'ThumbsUp'), (4, 'Nerve')], default=1)),
                ('likedBy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('automate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Automation.PostAutomation')),
                ('comments', models.ManyToManyField(null=True, to='SocialNode.Comment')),
                ('likes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialNode.Like')),
            ],
        ),
        migrations.CreateModel(
            name='SocialNodeState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialNode.Follower')),
                ('following', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialNode.Following')),
                ('friend', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialNode.Friend')),
                ('posts', models.ManyToManyField(null=True, related_name='Posts', to='SocialNode.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialNode.Like')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SocialNode.Like'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ManyToManyField(null=True, related_name='Reply', to='SocialNode.Reply'),
        ),
    ]
