# Generated by Django 2.2.3 on 2019-07-31 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=5000)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('video', models.FileField(null=True, upload_to='', verbose_name='video')),
            ],
        ),
        migrations.CreateModel(
            name='QuickReplyTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=1000)),
                ('templates', models.ManyToManyField(related_name='Templates', to='Messenger.QuickReplyTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='AutomatedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('quickReply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Messenger.QuickReply')),
            ],
        ),
    ]
